app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("mytest")

app$uploadFile(file = "iris_test.csv")
app$setInputs(plotHeight = 72.5)
app$setInputs(plotWidth = 80)
app$setInputs(variables = c("Sepal.Length", "Petal.Length"))
app$setInputs(fill2 = "#BB3F98")
app$setInputs(fill3 = "#2E4DA1")
app$setInputs(font = 12)
app$setInputs(size = 3)
app$setInputs(geom = c("bar", "errorbar", "point_noJitter", "stat", "seg"))
app$setInputs(shape1 = "21")
app$setInputs(shape2 = "24")
app$setInputs(shape3 = "22")
app$setInputs(plt2rprt = "click")
app$setInputs(variables = c("Sepal.Width", "Petal.Width"))
app$setInputs(plt2rprt = "click")
app$snapshot()
app$setInputs(loadPlot = "1")
app$setInputs(load = "click")
app$snapshot()
app$setInputs(loadPlot = "2")
app$setInputs(update = "click")
app$setInputs(navbar = "<h2 style=\"margin-top: 30px; margin-bottom: 30px\">Report</h2>")
Sys.sleep(10)
app$snapshot()
app$uploadFile(file = "iris_test.xlsx")
app$setInputs(sheet = c("iris_1", "iris_2"))
app$setInputs(refresh = "click")
Sys.sleep(10)
app$snapshot()
app$setInputs(clearAll = "click")
Sys.sleep(2)
app$snapshot()
app$setInputs(sampleFile = "click")
app$setInputs(method = "wilcox.test")
app$setInputs(method = "anova")
app$setInputs(method = "t.test")
