app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(geom = c("bar", "errorbar", "point_noJitter", "stat", "seg"))
app$setInputs(sampleFile = "click")
app$setInputs(plotHeight = 80)
app$setInputs(plotWidth = 100)
app$setInputs(variables = c("Sepal.Length", "Petal.Length"))
app$setInputs(fill2 = "#BB3F98")
app$setInputs(fill3 = "#2E4DA1")
app$setInputs(size = 3)
app$setInputs(font = 12)
app$snapshot()
app$setInputs(geom = c("violin", "stat", "seg"))
app$snapshot()
app$setInputs(plt2rprt = "click")
app$setInputs(geom = c("crossbar", "point_noJitter", "stat", "seg"))
app$setInputs(plt2rprt = "click")
app$setInputs(loadPlot = "1")
app$setInputs(load = "click")
app$setInputs(refreshData = "click")
app$setInputs(refresh = "click")
app$setInputs(loadPlot = "2")
app$setInputs(update = "click")
app$snapshot()
